USE Master;
GO

DROP DATABASE IF EXISTS RecipeManager;
GO

CREATE DATABASE RecipeManager;
GO

USE RecipeManager;

CREATE TABLE RecipeManager.dbo.UserTbl (
  Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
  CID INT IDENTITY(1,1) UNIQUE CLUSTERED NOT NULL,
  FName VARCHAR(40),
  LName VARCHAR(40),
  UName VARCHAR(25) NOT NULL
);

CREATE TABLE RecipeManager.dbo.UserAuthTbl(
  Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
  CID INT IDENTITY(1,1) UNIQUE CLUSTERED NOT NULL,
  UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES UserTbl(Id) NOT NULL,
  Salt UNIQUEIDENTIFIER NOT NULL,
  Iteration INT NOT NULL,
  PWord CHAR(128) NOT NULL,
  IsEnabled Bit
);

CREATE TABLE RecipeManager.dbo.RecipeTbl(
  Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
  CID INT IDENTITY(1,1) UNIQUE CLUSTERED NOT NULL,
  OwnerId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES UserTbl(Id) NOT NULL,
  Name VARCHAR(40) NOT NULL,
  Description VARCHAR(max), 
  IsPublic bit NOT NULL
);

CREATE TABLE RecipeManager.dbo.IngredientTbl(
  Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
  CID INT IDENTITY(1,1) UNIQUE CLUSTERED NOT NULL,
  RecipeId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES RecipeTbl(Id) NOT NULL,
  Name VARCHAR(40) NOT NULL,
  Units DECIMAL(10,2),
  UnitOfMeasure VARCHAR(80),
  Description VARCHAR(max)
);

CREATE TABLE RecipeManager.dbo.StepTbl(
  Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
  CID INT IDENTITY(1,1) UNIQUE CLUSTERED NOT NULL,
  RecipeId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES RecipeTbl(Id) NOT NULL,
  Name VARCHAR(40) NOT NULL,
  SortOrder INT NOT NULL,
  Detail VARCHAR(max),
  Duration DECIMAL(10,2),
  DurationUnit VARCHAR(40)
);

INSERT INTO RecipeManager.dbo.UserTbl (Id, FName, LName, UName) VALUES ('51000000-0000-0000-0000-000000000000', 'j','j', 'jmTest');